stages: 
  - build
  - test

build_project:
  stage: build
  script:
    - swift package clean
    - swift build
  tags:
    - swift
    - shopping-list
    - build


test_project:
  stage: test
  script:
    - swift test
  tags:
    - swift
    - shopping-list
    - test
