version: "3.7"

services: 

  shopping-list:
    image: shopping-list:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - backend
    volumes:
      - /var/log/:/var/log
  
  mongo:
    image: mongo:local
    build:
      context: .
      dockerfile: mongo.Dockerfile
    networks: 
      - backend
    volumes: 
      - mongo-data:/data/db
      
volumes: 
  mongo-data:

networks: 
  backend:
    